services:
  frps:
    image: frps
    build:
      context: .
      dockerfile: Dockerfile.frps
    container_name: frps
    restart: always
    volumes:
      - ./conf/frps.toml:/conf/frps.toml
    network_mode: "host"

  frpc:
    image: frpc
    build:
      context: .
      dockerfile: Dockerfile.frpc
    container_name: frpc
    restart: always
    volumes:
      - ./conf/frps.toml:/conf/frps.toml
    network_mode: "host"
