version: "3.9"
services:
  frpc:
    restart: always
    container_name: frpc
    image: frp
    build:
      context: frp
      dockerfile: "../myconf/frpc.Dockerfile"
    volumes:
      - "./myconf/frpc.ini:/frp/conf/frpc.ini"
    network_mode: host
    
  frps:
    restart: always
    container_name: frps
    image: frp
    build:
      context: frp
      dockerfile: "../myconf/frps.Dockerfile"
    volumes:
      - "./myconf/frps.ini:/frp/conf/frps.ini"
    network_mode: host
